const products = [
  { id:'navy-suit', name:'Bộ suit Navy Roma', category:'suits', categoryName:'Suit may đo', tag:'Nexus Essential', price:8900000, originalPrice:8900000, rating:0, reviewsCount:0, image:'assets/images/menswear/navy-suit.png', shortDescription:'Phom vai tự nhiên, ve notch cân đối và quần ly đôi cho những dịp cần sự chỉnh chu.', description:'Bộ suit hai mảnh màu navy với cấu trúc nhẹ, phom regular tailored và bề mặt vải lì. Thiết kế ưu tiên tỷ lệ gọn gàng và khả năng phối đồ linh hoạt.', specs:{diameter:'46–54',thickness:'Regular tailored',movement:'Wool blend',glass:'Navy',caseMaterial:'Vải dệt trơn',strap:'Jacket & trousers',waterResistance:'Giặt khô',warranty:'Chỉnh sửa phom theo chính sách cửa hàng'}, highlights:['Cấu trúc vai nhẹ','Ve notch cổ điển','Quần ly đôi'] },
  { id:'ivory-shirt', name:'Sơ mi Ivory Firenze', category:'shirts', categoryName:'Sơ mi', tag:'Core Wardrobe', price:1650000, originalPrice:1650000, rating:0, reviewsCount:0, image:'assets/images/menswear/ivory-shirt.png', shortDescription:'Sơ mi cotton màu ivory với cổ spread, đường may sạch và phom dễ mặc cùng tailoring.', description:'Mẫu sơ mi nền tảng cho tủ đồ nam, được thiết kế với cổ spread vừa phải và thân áo gọn. Sắc ivory dịu hơn trắng quang học, phù hợp cả trang phục công sở lẫn smart casual.', specs:{diameter:'S–XXL',thickness:'Tailored fit',movement:'Cotton',glass:'Ivory',caseMaterial:'Vải dệt mịn',strap:'Spread collar',waterResistance:'Giặt máy nhẹ',warranty:'Theo chính sách đổi trả'}, highlights:['Cổ spread','Nẹp nút gọn','Tà cong dễ sơ vin'] },
  { id:'charcoal-trousers', name:'Quần ly đôi Milano', category:'trousers', categoryName:'Quần may đo', tag:'New Cut', price:2450000, originalPrice:2450000, rating:0, reviewsCount:0, image:'assets/images/menswear/charcoal-trousers.png', shortDescription:'Cạp cao vừa, hai ly xuôi và ống thẳng tạo độ rũ tự nhiên khi di chuyển.', description:'Quần charcoal cạp cao vừa với hai ly xuôi, ống thẳng và phần gấu sạch. Tỷ lệ được thiết kế để mặc cùng blazer hoặc sơ mi độc lập.', specs:{diameter:'29–36',thickness:'Straight fit',movement:'Wool blend',glass:'Charcoal',caseMaterial:'Vải dệt lì',strap:'Double pleat',waterResistance:'Giặt khô',warranty:'Theo chính sách đổi trả'}, highlights:['Cạp cao vừa','Hai ly xuôi','Gấu quần may sạch'] },
  { id:'tobacco-blazer', name:'Blazer Linen Siena', category:'jackets', categoryName:'Blazer', tag:'Linen Edit', price:4950000, originalPrice:4950000, rating:0, reviewsCount:0, image:'assets/images/menswear/tobacco-blazer.png', shortDescription:'Blazer linen màu tobacco, cấu trúc mềm và ba túi đắp cho những ngày cần sự thoải mái.', description:'Blazer linen một lớp với vai tự nhiên, ve notch và túi đắp. Tông tobacco ấm phù hợp quần ivory, denim sẫm hoặc quần charcoal.', specs:{diameter:'46–54',thickness:'Relaxed tailored',movement:'Linen blend',glass:'Tobacco',caseMaterial:'Vải linen có vân',strap:'Patch pockets',waterResistance:'Giặt khô',warranty:'Theo chính sách đổi trả'}, highlights:['Vai mềm','Ba túi đắp','Cấu trúc nhẹ'] }
];
function formatVND(amount){return amount.toLocaleString('vi-VN')+' ₫';}
function getStoredCart(){try{const raw=localStorage.getItem('nexus_luxury_cart');const cart=raw?JSON.parse(raw):{};return Object.fromEntries(Object.entries(cart).filter(([id])=>products.some(product=>product.id===id)));}catch(e){return{};}}
function saveStoredCart(cartObj){try{localStorage.setItem('nexus_luxury_cart',JSON.stringify(cartObj));}catch(e){}}
function getStoredWishlist(){try{const raw=localStorage.getItem('nexus_luxury_wishlist');const list=raw?JSON.parse(raw):[];return list.filter(id=>products.some(product=>product.id===id));}catch(e){return[];}}
function saveStoredWishlist(list){try{localStorage.setItem('nexus_luxury_wishlist',JSON.stringify(list));}catch(e){}}
